export const AdminActionType = {
  USER_LIST_REQUEST: "USER_LIST_REQUEST",
  USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
  USER_LIST_FAIL: "USER_LIST_FAIL",

  USER_APPROVAL_REQUEST: "USER_APPROVAL_REQUEST",
  USER_APPROVAL_SUCCESS: "USER_APPROVAL_SUCCESS",
  USER_APPROVAL_FAIL: "USER_APPROVAL_FAIL",

  COUNTRY_ADD_REQUEST: "COUNTRY_ADD_REQUEST",
  COUNTRY_ADD_SUCCESS: "COUNTRY_ADD_SUCCESS",
  COUNTRY_ADD_FAIL: "COUNTRY_ADD_FAIL",

  COUNTRY_LIST_REQUEST: "COUNTRY_LIST_REQUEST",
  COUNTRY_LIST_SUCCESS: "COUNTRY_LIST_SUCCESS",
  COUNTRY_LIST_FAIL: "COUNTRY_LIST_FAIL",

  COUNTRY_DELETE_REQUEST: "COUNTRY_DELETE_REQUEST",
  COUNTRY_DELETE_SUCCESS: "COUNTRY_DELETE_SUCCESS",
  COUNTRY_DELETE_FAIL: "COUNTRY_DELETE_FAIL",

  COUNTRY_UPDATE_REQUEST: "COUNTRY_UPDATE_REQUEST",
  COUNTRY_UPDATE_SUCCESS: "COUNTRY_UPDATE_SUCCESS",
  COUNTRY_UPDATE_FAIL: "COUNTRY_UPDATE_FAIL",

  STATE_ADD_REQUEST: "STATE_ADD_REQUEST",
  STATE_ADD_SUCCESS: "STATE_ADD_SUCCESS",
  STATE_ADD_FAIL: "STATE_ADD_FAIL",

  STATE_LIST_SUCCESS: "STATE_LIST_SUCCESS",
  STATE_LIST_REQUEST: "STATE_LIST_REQUEST",
  STATE_LIST_FAIL: "STATE_LIST_FAIL",

  STATE_DELETE_REQUEST: "STATE_DELETE_REQUEST",
  STATE_DELETE_SUCCESS: "STATE_DELETE_SUCCESS",
  STATE_DELETE_FAIL: "STATE_DELETE_FAIL",

  STATE_UPDATE_REQUEST: "STATE_UPDATE_REQUEST",
  STATE_UPDATE_SUCCESS: "STATE_UPDATE_SUCCESS",
  STATE_UPDATE_FAIL: "STATE_UPDATE_FAIL",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",

  ADD_COMPLAINT_CATEGORY_REQUEST: "ADD_COMPLAINT_CATEGORY_REQUEST",
  ADD_COMPLAINT_CATEGORY_SUCCESS: "ADD_COMPLAINT_CATEGORY_SUCCESS",
  ADD_COMPLAINT_CATEGORY_FAIL: "ADD_COMPLAINT_CATEGORY_FAIL",

  COMPLAINT_CATEGORY_LIST_REQUEST: "COMPLAINT_CATEGORY_LIST_REQUEST",
  COMPLAINT_CATEGORY_LIST_SUCCESS: "COMPLAINT_CATEGORY_LIST_SUCCESS",
  COMPLAINT_CATEGORY_LIST_FAIL: "COMPLAINT_CATEGORY_LIST_FAIL",

  COMPLAINT_CATEGORY_DELETE_REQUEST: "COMPLAINT_CATEGORY_DELETE_REQUEST",
  COMPLAINT_CATEGORY_DELETE_SUCCESS: "COMPLAINT_CATEGORY_DELETE_SUCCESS",
  COMPLAINT_CATEGORY_DELETE_FAIL: "COMPLAINT_CATEGORY_DELETE_FAIL",

  COMPLAINT_CATEGORY_UPDATE_REQUEST: "COMPLAINT_CATEGORY_UPDATE_REQUEST",
  COMPLAINT_CATEGORY_UPDATE_SUCCESS: "COMPLAINT_CATEGORY_UPDATE_SUCCESS",
  COMPLAINT_CATEGORY_UPDATE_FAIL: "COMPLAINT_CATEGORY_UPDATE_FAIL",

  ADD_COMPLAINT_SUB_CATEGORY_REQUEST: "ADD_COMPLAINT_SUB_CATEGORY_REQUEST",
  ADD_COMPLAINT_SUB_CATEGORY_SUCCESS: "ADD_COMPLAINT_SUB_CATEGORY_SUCCESS",
  ADD_COMPLAINT_SUB_CATEGORY_FAIL: "ADD_COMPLAINT_SUB_CATEGORY_FAIL",

  COMPLAINT_SUB_CATEGORY_LIST_REQUEST: "COMPLAINT_SUB_CATEGORY_LIST_REQUEST",
  COMPLAINT_SUB_CATEGORY_LIST_SUCCESS: "COMPLAINT_SUB_CATEGORY_LIST_SUCCESS",
  COMPLAINT_SUB_CATEGORY_LIST_FAIL: "COMPLAINT_SUB_CATEGORY_LIST_FAIL",

  COMPLAINT_SUB_CATEGORY_DELETE_REQUEST:
    "COMPLAINT_SUB_CATEGORY_DELETE_REQUEST",
  COMPLAINT_SUB_CATEGORY_DELETE_SUCCESS:
    "COMPLAINT_SUB_CATEGORY_DELETE_SUCCESS",
  COMPLAINT_SUB_CATEGORY_DELETE_FAIL: "COMPLAINT_SUB_CATEGORY_DELETE_FAIL",

  COMPLAINT_SUBCAT_UPDATE_REQUEST: "COMPLAINT_SUBCAT_UPDATE_REQUEST",
  COMPLAINT_SUBCAT_UPDATE_SUCCESS: "COMPLAINT_SUBCAT_UPDATE_SUCCESS",
  COMPLAINT_SUBCAT_UPDATE_FAIL: "COMPLAINT_SUBCAT_UPDATE_FAIL",

  ADD_COMPLAINT_REMARKS_REQUEST: "ADD_COMPLAINT_REMARKS_REQUEST",
  ADD_COMPLAINT_REMARKS_SUCCESS: "ADD_COMPLAINT_REMARKS_SUCCESS",
  ADD_COMPLAINT_REMARKS_FAIL: "ADD_COMPLAINT_REMARKS_FAIL",

  LIST_COMPLAINT_REMARKS_REQUEST: "LIST_COMPLAINT_REMARKS_REQUEST",
  LIST_COMPLAINT_REMARKS_SUCCESS: "LIST_COMPLAINT_REMARKS_SUCCESS",
  LIST_COMPLAINT_REMARKS_FAIL: "LIST_COMPLAINT_REMARKS_FAIL",

  COMPLAINT_REMARKS_UPDATE_REQUEST: "COMPLAINT_REMARKS_UPDATE_REQUEST",
  COMPLAINT_REMARKS_UPDATE_SUCCESS: "COMPLAINT_REMARKS_UPDATE_SUCCESS",
  COMPLAINT_REMARKS_UPDATE_FAIL: "COMPLAINT_REMARKS_UPDATE_FAIL",
};
