export const AdminActionType = {
  USER_LIST_REQUEST: "USER_LIST_REQUEST",
  USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
  USER_LIST_FAIL: "USER_LIST_FAIL",

  USER_APPROVAL_REQUEST: "USER_APPROVAL_REQUEST",
  USER_APPROVAL_SUCCESS: "USER_APPROVAL_SUCCESS",
  USER_APPROVAL_FAIL: "USER_APPROVAL_FAIL",

  COUNTRY_ADD_REQUEST: "COUNTRY_ADD_REQUEST",
  COUNTRY_ADD_SUCCESS: "COUNTRY_ADD_SUCCESS",
  COUNTRY_ADD_FAIL: "COUNTRY_ADD_FAIL",

  COUNTRY_LIST_REQUEST: "COUNTRY_LIST_REQUEST",
  COUNTRY_LIST_SUCCESS: "COUNTRY_LIST_SUCCESS",
  COUNTRY_LIST_FAIL: "COUNTRY_LIST_FAIL",

  STATE_ADD_REQUEST: "STATE_ADD_REQUEST",
  CSTATE_ADD_SUCCESS: "STATE_ADD_SUCCESS",
  STATE_ADD_FAIL: "STATE_ADD_FAIL",

  STATE_LIST_SUCCESS: "STATE_LIST_SUCCESS",
  STATE_LIST_REQUEST: "STATE_LIST_REQUEST",
  STATE_LIST_FAIL: "STATE_LIST_FAIL",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_REQUEST",
};
