export const UserActionType = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  USER_LOGOUT: "USER_LOGOUT",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

  USER_LIST_REQUEST: "USER_LIST_REQUEST",
  USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
  USER_LIST_FAIL: "USER_LIST_FAIL",
  USER_APPROVAL_REQUEST: "USER_APPROVAL_REQUEST",
  USER_APPROVAL_SUCCESS: "USER_APPROVAL_SUCCESS",
  USER_APPROVAL_FAIL: "USER_APPROVAL_FAIL",

  COMPLAINT_REGISTER_REQUEST: "COMPLAINT_REGISTER_REQUEST",
  COMPLAINT_REGISTER_SUCCESS: "COMPLAINT_REGISTER_SUCCESS",
  COMPLAINT_REGISTER_FAIL: "COMPLAINT_REGISTER_FAIL",

  LIST_COMPLAINT_REQUEST: "LIST_COMPLAINT_REQUEST",
  LIST_COMPLAINT_SUCCESS: "LIST_COMPLAINT_SUCCESS",
  LIST_COMPLAINT_FAIL: "LIST_COMPLAINT_FAIL",

  UPDATE_COMPLAINT_REQUEST: "UPDATE_COMPLAINT_REQUEST",
  UPDATE_COMPLAINT_SUCCESS: "UPDATE_COMPLAINT_SUCCESS",
  UPDATE_COMPLAINT_FAIL: "UPDATE_COMPLAINT_FAIL",

  PROFILE_REGISTER_REQUEST: "PROFILE_REGISTER_REQUEST",
  PROFILE_REGISTER_SUCCESS: "PROFILE_REGISTER_SUCCESS",
  PROFILE_REGISTER_FAIL: "PROFILE_REGISTER_FAIL",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",

  FEEDBACK_ADD_REQUEST: "FEEDBACK_ADD_REQUEST",
  FEEDBACK_ADD_SUCCESS: "FEEDBACK_ADD_SUCCESS",
  FEEDBACK_ADD_FAIL: "FEEDBACK_ADD_FAIL",

  FEEDBACK_LIST_REQUEST: "FEEDBACK_LIST_REQUEST",
  FEEDBACK_LIST_SUCCESS: "FEEDBACK_LIST_SUCCESS",
  FEEDBACK_LIST_FAIL: "FEEDBACK_LIST_FAIL",
};
